revamped release-bottle
More checking of JSON output, and proper use of `gh release` even when there's no bottle stanza.

diff --git a/brew-release-bottle b/brew-release-bottle
--- a/brew-release-bottle
+++ b/brew-release-bottle
@@ -8,11 +8,17 @@ cleanup() {
   tmpdir=""
 }
 
-shopt -s lastpipe
-if ! command -v jq &>/dev/null; then
-  echo "FATAL ERROR: jq not available, aborting."
+fatal() {
+  echo "FATAL ERROR: $*" >&2
   exit 1
-fi
+}
+
+jquery() {
+  jq -r ".[] | $*" ./.base_json
+}
+
+shopt -s lastpipe
+command -v jq &>/dev/null || fatal "jq not available"
 
 set -e
 
@@ -20,17 +26,36 @@ for f in "$@"; do
   if [[ $f =~ ([^/]+)/([^/]+)/([^/]+) ]]; then
     tap=${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
     ghrepo=${BASH_REMATCH[1]}/homebrew-${BASH_REMATCH[2]}
+    repodir=$(brew --repo "$ghrepo")
     fname=${BASH_REMATCH[3]}
     tmpdir=$(mktemp -d)
     cd "$tmpdir"
     echo "===== Bottling $f in $tmpdir ====="
     brew install --build-bottle "$f"
-    root_url=$(brew info --json "$f" | jq -r '.[] | .bottle.stable.root_url')
-    brew bottle --verbose --json --root-url="$root_url" "$f"
-    brew bottle --merge --write --root-url="$root_url" --keep-old ./*.json
+    brew info --json "$f" > ./.base_json
+    fver=$(jquery .versions.stable)
+    if [[ $(jquery '.bottle | length') == "0" && -s ${repodir}/.root_url_base ]]; then
+      # New bottle section
+      root_url=https://github.com/${ghrepo}/releases/download/${fname}-${fver}
+      keep_old=()
+    else
+      root_url=$(jquery .bottle.stable.root_url)
+      keep_old=(--keep-old)
+    fi
+    [[ $root_url != "null" ]] || fatal "unable to determine root URL"
+    brew bottle --verbose --json --root-url="${root_url}" "$f"
+    brew bottle --merge --write --root-url="${root_url}" "${keep_old[@]}" ./*.json
     echo "----- Uploading for $f -----"
     jq -r '.[].bottle.tags|.[]|"\(.local_filename) \(.filename)"' ./*.json | while read lf rf; do
-      mv -v "$lf" "$rf" && gh release upload "${root_url##*/}" "$rf" -R "$ghrepo" --clobber
+      mv -v "$lf" "$rf"
+      tag=${root_url##*/}
+      if gh release view "$tag" -R "$ghrepo" >&/dev/null; then
+        # Release already created
+        gh release upload "$tag" "$rf" -R "$ghrepo" --clobber
+      else
+        # We need to create it with this new file
+        gh release create "$tag" "$rf" -R "$ghrepo"
+      fi
     done
     git -C $(brew --repo "$tap") push 
     echo "----- Reinstalling $f -----"
