Get necessary refs from repo itself
Instead of hardcoding values that don't always apply

diff --git a/brew-rm-pr-branch b/brew-rm-pr-branch
--- a/brew-rm-pr-branch
+++ b/brew-rm-pr-branch
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash
+if mainbranch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null); then
+  mainbranch=${mainbranch##*/}
+else
+  echo "FATAL ERROR: Not in Git repo"
+  exit 1
+fi
 currbranch=$(git branch --show-current)
 if [[ $# -eq 0 ]]; then
   git branch -a
   exit 1
 fi
 for b in "$@"; do
-  [[ $b == $currbranch ]] && git checkout master
-  git push -d gromgit $b && git branch -D $b
+  [[ $b == $currbranch ]] && git checkout ${mainbranch}
+  upstream=$(git rev-parse --abbrev-ref ${b}@{upstream})
+  git push -d ${upstream/\// } && git branch -D $b
 done
 git branch -a
